Bigger indentation for readability.

diff --git a/debian/tahoe-lafs.init b/debian/tahoe-lafs.init
--- a/debian/tahoe-lafs.init
+++ b/debian/tahoe-lafs.init
@@ -25,7 +25,7 @@ DAEMONARGS="--syslog"
 AUTOSTART=""
 
 if test -e /etc/default/tahoe-lafs; then
-  . /etc/default/tahoe-lafs
+    . /etc/default/tahoe-lafs
 fi
 
 get_node_uid () {
@@ -40,12 +40,12 @@ start_tahoe () {
     get_node_uid $NAME
 
     if [ $UID -ne 0 ]; then
-      start-stop-daemon --start --quiet --oknodo \
-          --pidfile $CONFIG_DIR/$NAME/twistd.pid \
-          --exec $DAEMON --chuid $UID -- start $DAEMONARGS \
-	  $CONFIG_DIR/$NAME 1> /dev/null|| STATUS=1
+        start-stop-daemon --start --quiet --oknodo \
+            --pidfile $CONFIG_DIR/$NAME/twistd.pid \
+            --exec $DAEMON --chuid $UID -- start $DAEMONARGS \
+	    $CONFIG_DIR/$NAME 1> /dev/null|| STATUS=1
     else
-      log_failure_msg "$NAME node directory shouldn't be owned by root!"
+        log_failure_msg "$NAME node directory shouldn't be owned by root!"
     fi
 }
 
@@ -55,80 +55,79 @@ stop_tahoe () {
 
 case "$1" in
 start)
-  log_daemon_msg "Starting $DESC"
+    log_daemon_msg "Starting $DESC"
 
-  if test -z "$2" ; then
-    if test "x$AUTOSTART" = "xnone" -o -z "$AUTOSTART" ; then
-      log_warning_msg " Autostart disabled."
-      exit 0
-    fi
-    if test -z "$AUTOSTART" -o "x$AUTOSTART" = "xall" ; then
-      # all nodes shall be started automatically
-      for NAME in `cd $CONFIG_DIR; find ./ -mindepth 1 -maxdepth 1 -type d | cut -c3-  2> /dev/null`; do
-        start_tahoe
-      done
-    else
-      # start only specified nodes
-      for NAME in $AUTOSTART ; do
-        if test -d $CONFIG_DIR/$NAME ; then
-          start_tahoe
-        else
-          log_failure_msg "No such node configured: $NAME"
-          STATUS=1
+    if test -z "$2" ; then
+        if test "x$AUTOSTART" = "xnone" -o -z "$AUTOSTART" ; then
+            log_warning_msg " Autostart disabled."
+            exit 0
         fi
-      done
+        if test -z "$AUTOSTART" -o "x$AUTOSTART" = "xall" ; then
+        # all nodes shall be started automatically
+            for NAME in `cd $CONFIG_DIR; find ./ -mindepth 1 -maxdepth 1 -type d | cut -c3-  2> /dev/null`; do
+                start_tahoe
+            done
+        else
+        # start only specified nodes
+        for NAME in $AUTOSTART ; do
+            if test -d $CONFIG_DIR/$NAME ; then
+                start_tahoe
+            else
+                log_failure_msg "No such node configured: $NAME"
+                STATUS=1
+            fi
+        done
     fi
-  else
-    while shift ; do
-      [ -z "$1" ] && break
-      NAME=$1
-      if test -d $CONFIG_DIR/$NAME ; then
-        start_tahoe
-      else
-       log_failure_msg " No such node configured: $NAME"
-       STATUS=1
-      fi
-    done
-  fi
-  log_end_msg ${STATUS:-0}
-
-  ;;
+    else
+        while shift ; do
+            [ -z "$1" ] && break
+            NAME=$1
+            if test -d $CONFIG_DIR/$NAME ; then
+                start_tahoe
+            else
+               log_failure_msg " No such node configured: $NAME"
+               STATUS=1
+            fi
+        done
+    fi
+    log_end_msg ${STATUS:-0}
+    ;;
 stop)
-  log_daemon_msg "Stopping $DESC"
+    log_daemon_msg "Stopping $DESC"
 
-  if test -z "$2" ; then
-    for PIDFILE in `find $CONFIG_DIR -name twistd.pid 2> /dev/null`; do
-      NAME=`echo $PIDFILE | cut -c21- | sed -e 's/\/twistd.pid//'`
-      stop_tahoe
-      log_progress_msg "$NAME"
-    done
-  else
-    while shift ; do
-      [ -z "$1" ] && break
-      NAME=$1
-      if test -e $CONFIG_DIR/$NAME/twistd.pid ; then
-        stop_tahoe
-        log_progress_msg "$NAME"
-      else
-        log_failure_msg " (failure: No such node running: $NAME)"
-      fi
-    done
-  fi
-  log_end_msg ${STATUS:-0}
-  ;;
+    if test -z "$2" ; then
+        for PIDFILE in `find $CONFIG_DIR -name twistd.pid 2> /dev/null`; do
+            NAME=`echo $PIDFILE | cut -c21- | sed -e 's/\/twistd.pid//'`
+            stop_tahoe
+            log_progress_msg "$NAME"
+        done
+    else
+        while shift ; do
+            [ -z "$1" ] && break
+            NAME=$1
+            if test -e $CONFIG_DIR/$NAME/twistd.pid ; then
+                stop_tahoe
+                log_progress_msg "$NAME"
+            else
+                log_failure_msg " (failure: No such node running: $NAME)"
+            fi
+        done
+    fi
+    log_end_msg ${STATUS:-0}
+    ;;
 restart)
-  shift
-  $0 stop ${@}
-  sleep 1
-  $0 start ${@}
-  ;;
+    shift
+    $0 stop ${@}
+    sleep 1
+    $0 start ${@}
+    ;;
 force-reload)
-  $0 restart ${@}
-  ;;
+    $0 restart ${@}
+    ;;
 *)
-  echo "Usage: $0 {start|stop|restart|force-reload}" >&2
-  exit 1
-  ;;
+    echo "Usage: $0 {start|stop|restart|force-reload}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
